const data = {
    upper : [
        {
            name: "Seated Arm Circles",
            subName : "Shoulder mobility, gradual arm strength", 
            desc: "Sit in a chair, extend arms, and make small circles in the air", 
            mode: "Easy", 
            disabilityType: "Arm mobility limitations", 
            bodyParts: "Arms",
            image: "assets/report_1/upper body/Seated Arm Circles.png", 
        },
        {
            name: "Resistance Band Bicep Curls", 
            subName : "Builds bicep strength", 
            desc: "Place resistance band under feet; hold with palms up and curl arms toward shoulders", 
            mode: "Easy", 
            disabilityType: "Arm and wrist limitations", 
            bodyParts: "Biceps",
            image: "assets/report_1/upper body/Resistance Band Bicep Curls.webp", 
        },
        {
            name: "Tricep Extensions (Seated)", 
            subName : "Works triceps", 
            desc: "Hold a weight or band behind head and extend arms up, focusing on triceps", 
            mode: "Medium", 
            disabilityType: "Arm mobility limitations", 
            bodyParts: "Triceps",
            image: "assets/report_1/upper body/Tricep Extensions (Seated).jpeg", 
        },
        {
            name: "Isometric Shoulder Press (Without Weights)", 
            subName : "Strengthens shoulders by pressing palms together", 
            desc: "Press palms together in front of chest, activating shoulders", 
            mode: "Easy", 
            disabilityType: "Shoulder strength limitations", 
            bodyParts: "Shoulder",
            image: "assets/report_1/upper body/Isometric Shoulder Press (Without Weights).png", 
        },
        {
            name: "Wrist Curls (With Light Weights)", 
            subName : "Strengthens forearm and wrist", 
            desc: "Hold light weights, curl wrists up and down slowly", 
            mode: "Easy", 
            disabilityType: "Limited wrist mobility", 
            bodyParts: "Wrist",
            image: "assets/report_1/upper body/Wrist Curls (With Light Weights).jpg", 
        },
        {
            name: "Seated Wrist Rotations", 
            subName : "Improves wrist mobility", 
            desc: "Rotate wrists in a circular motion while seated to improve mobility", 
            mode: "Easy", 
            disabilityType: "Limited wrist mobility", 
            bodyParts: "Wrist",
            image: "assets/report_1/upper body/Seated Wrist Rotations.webp", 
        }
    ], 
    lower : [
        {
            name: "Seated Leg Extensions",
            subName : "Engages quadriceps", 
            desc: "While seated, extend one leg out straight, hold, and lower it back", 
            mode: "Easy", 
            disabilityType: "Leg disabilities, wheelchair users", 
            bodyParts: "Quadriceps",
            image: "assets/report_1/lower body/Seated Leg Extensions.webp", 
        },
        {
            name: "Ankle Flexion/Extension with Resistance Band", 
            subName : "Supports ankle mobility and calf strength", 
            desc: "Use a resistance band to flex and extend the ankle", 
            mode: "Easy", 
            disabilityType: "Lower leg limitations", 
            bodyParts: "Ankles",
            image: "assets/report_1/lower body/Ankle Flexion Extension with Resistance Band.jpg", 
        },
        {
            name: "Wheelchair Toe Raises", 
            subName : "Works calf muscles", 
            desc: "Lift toes off the ground while keeping heels down", 
            mode: "Easy", 
            disabilityType: "Lower leg limitations", 
            bodyParts: "Calves",
            image: "assets/report_1/lower body/Wheelchair Toe Raises.webp", 
        },
        {
            name: "Knee Lifts (Seated or with Support)", 
            subName : "Strengthens quadriceps and hip flexors", 
            desc: "Lift knees alternately while seated, focusing on quadriceps", 
            mode: "Easy", 
            disabilityType: "Leg disabilitie", 
            bodyParts: "Hips",
            image: "assets/report_1/lower body/KNEE lifts (2).webp", 
        },
        {
            name: "Seated Marches (High Knees)", 
            subName : "Engages hip flexors and upper thighs", 
            desc: "Raise each knee alternately while seated, simulating marching", 
            mode: "Medium", 
            disabilityType: "Lower body limitations", 
            bodyParts: "Thighs",
            image: "assets/report_1/lower body/Seated Marches (High Knees) (2).webp", 
        },
        {
            name: "Foot Circles", 
            subName : "Enhances ankle flexibility", 
            desc: "Move feet in circular motion to improve ankle mobility", 
            mode: "Easy", 
            disabilityType: "Ankle flexibility limitations", 
            bodyParts: "Ankles",
            image: "assets/report_1/lower body/Foot Circles (2).webp", 
        }

    ], 
    core : [
        {
            name: "Seated Torso Twists",
            subName : "Engages core muscles", 
            desc: "Twist torso from side to side while seated", 
            mode: "Easy", 
            disabilityType: "ACore mobility limitations", 
            bodyParts: "Core",
            image: "assets/report_1/core/Seated Torso Twists (2).webp", 
        },
        {
            name: "Modified Russian Twists (Supported Back)", 
            subName : "Targets obliques", 
            desc: "Twist torso from side to side while holding a light weight", 
            mode: "Medium", 
            disabilityType: "Core and oblique limitations", 
            bodyParts: "Core, Obliques",
            image: "assets/report_1/core/Modified Russian Twists.webp", 
        },
        {
            name: "Seated Leg Raises (Supported)", 
            subName : "Strengthens lower abs", 
            desc: "Lift legs up slightly off the ground while seated", 
            mode: "Medium", 
            disabilityType: "Lower abs and hip flexors", 
            bodyParts: "Lower Abs",
            image: "assets/report_1/core/Seated Leg Raises.webp", 
        },
        {
            name: "Pelvic Tilts (Seated or Reclined)", 
            subName : "Strengthens lower core", 
            desc: "Contract abs and tilt pelvis forward and back", 
            mode: "Easy", 
            disabilityType: "Lower core strength", 
            bodyParts: "Lower Core",
            image: "assets/report_1/core/Pelvic Tilts.webp", 
        },
        {
            name: "Seated Knee Tucks", 
            subName : "Engages lower abs and hip flexors", 
            desc: "Pull knees toward chest and release while seated", 
            mode: "Medium", 
            disabilityType: "Core, lower abs limitations", 
            bodyParts: "Hip Flexors",
            image: "assets/report_1/core/Seated Knee Tucks.webp", 
        },
        {
            name: "Isometric Core Hold (Seated)", 
            subName : "Helps develop core strength by holding a braced position", 
            desc: "Engage core muscles, holding a braced position while seated", 
            mode: "Easy", 
            disabilityType: "Core strength", 
            bodyParts: "Core",
            image: "assets/report_1/core/Isometric Core Hold (Seated).webp", 
        }
    ],
    back : [
        {
            name: "Seated Rows (Resistance Band)",
            subName : "Targets upper back muscles", 
            desc: "Sit in a chair, extend arms, and make small circles in the air", 
            mode: "Medium", 
            disabilityType: "Pull resistance band towards chest, keeping elbows close to the body", 
            bodyParts: "Upper Back",
            image: "assets/report_1/back/Seated Rows (Resistance Band).webp", 
        },
        {
            name: "Chest Expansions (Seated with Band)", 
            subName : "Strengthens chest and back", 
            desc: "Stretch resistance band in front of chest, squeezing shoulder blades together", 
            mode: "Easy", 
            disabilityType: "Back and chest strength", 
            bodyParts: "Chest",
            image: "assets/report_1/back/Chest Expansions (Seated with Band).jpg", 
        },
        {
            name: "Supported Back Extensions", 
            subName : "Builds lower back strength", 
            desc: "Lean back while seated, engaging lower back muscles, then return upright", 
            mode: "Medium", 
            disabilityType: "Lower back strength", 
            bodyParts: "Lower Back",
            image: "assets/report_1/back/Supported Back Extensions.jpg", 
        },
        {
            name: "Wall-Assisted Seated Lat Pull", 
            subName : "Engages lats and back", 
            desc: "Pull resistance band down from a high point, engaging back muscles", 
            mode: "Medium", 
            disabilityType: "Upper back mobility limitations", 
            bodyParts: "Lats",
            image: "assets/report_1/back/Wall-Assisted Seated Lat Pull.webp", 
        },
        {
            name: "Scapular Squeezes", 
            subName : "Strengthens upper back and posture", 
            desc: "Squeeze shoulder blades together, hold, and release", 
            mode: "Easy", 
            disabilityType: "Postural muscle limitations", 
            bodyParts: "Upper Back",
            image: "assets/report_1/back/Scapular Squeezes.webp", 
        },
        {
            name: "Arm Reach Backs (Seated)", 
            subName : "Works upper back and shoulders", 
            desc: "Extend arms behind body, stretching upper back muscles", 
            mode: "Easy", 
            disabilityType: "Upper back and shoulders", 
            bodyParts: "Shoulders",
            image: "assets/report_1/back/Arm Reach Backs.webp", 
        }
    ],
    shoulder : [
        {
            name: "Shoulder Press (Seated, with Light Weights)",
            subName : "Works shoulders", 
            desc: "Press light weights overhead while seated", 
            mode: "Medium", 
            disabilityType: "Shoulder strength limitations", 
            bodyParts: "Shoulders",
            image: "assets/report_1/shoulder/Shoulder Press Seated.webp", 
        },
        {
            name: "Front Arm Raises (With Dumbbell or Band)", 
            subName : "Targets front shoulder muscles", 
            desc: "Lift arms straight up in front of body, using a light weight", 
            mode: "Easy", 
            disabilityType: "Shoulder mobility limitations", 
            bodyParts: "Front Shoulders",
            image: "assets/report_1/shoulder/Front Arm Raises.webp", 
        },
        {
            name: "Lateral Raises (Modified Range)", 
            subName : "Engages side deltoids", 
            desc: "Lift arms out to the sides with light weights", 
            mode: "Medium", 
            disabilityType: "Shoulder mobility limitations", 
            bodyParts: "Side Shoulders",
            image: "assets/report_1/shoulder/Lateral Raises (Modified Range).webp", 
        },
        {
            name: "Seated Shoulder Shrugs", 
            subName : "Strengthens trapeziusr", 
            desc: "Shrug shoulders up towards ears, hold briefly, and release", 
            mode: "Easy", 
            disabilityType: "Trapezius strength", 
            bodyParts: "Traps",
            image: "assets/placeHolder.jpg", 
        },
        {
            name: "Overhead Band Pull-Aparts", 
            subName : "Targets shoulders and improves shoulder mobility", 
            desc: "Hold band overhead and pull it apart, engaging shoulder muscles", 
            mode: "Medium", 
            disabilityType: "Shoulder mobility and strength", 
            bodyParts: "Shoulders",
            image: "assets/placeHolder.jpg", 
        },
        {
            name: "Scapular Stability Holds", 
            subName : "Strengthens scapular muscles", 
            desc: "Hold arms in position to stabilize scapula for a few seconds", 
            mode: "Easy", 
            disabilityType: "Scapular muscle limitations", 
            bodyParts: "Scapular Muscles",
            image: "assets/placeHolder.jpg", 
        }
    ]
}

module.exports = data;